Repository choyeon2e/11th-FE-Networking-May, pull requests merged in 2025-05, with the labels that each got.

#5 [feat] 날씨 기능 구현 및 conflict 해결
  package.json
  public/index.html
  src/apis/axios.js
  src/apis/weatherMock.js
  src/assets/icon/ChevronLeft.jsx
  src/assets/icon/ChevronRight.jsx
  src/component/index.js
  src/component/location/DeleteModal.jsx
  src/component/location/Location.jsx
  src/component/location/LocationList.jsx
  src/component/location/LocationModal.jsx
  src/component/location/NoLocation.jsx
  src/component/weather/CurrentWeather.jsx
  src/component/weather/HourlyWeather.jsx
  src/component/weather/Weather.jsx
  src/component/weather/WeekWeather.jsx
  src/component/weather/details/AirBox.jsx
  src/component/weather/details/AirDetail.jsx
  src/component/weather/details/TempWeather.jsx
  src/hooks/useDebounce.jsx
  src/index.jsx
  src/pages/Main.jsx
  src/pages/Weather.jsx
  src/styles/palette.js
  src/utils/TempGraph.jsx
  src/utils/getDustLevel.js
  src/utils/getUVLevel.js
  src/utils/iconMapper.js
  src/utils/weatherStyles.js
  yarn.lock
Labels: Feat

#9 [Feat] 남은 api 연결 & 코드리뷰 반영 리팩토링
  src/apis/axios.js
  src/apis/fetchLocation.js
  src/apis/fetchWeather.js
  src/assets/icon/TrashCanIcon.jsx
  src/component/location/LocationDiv.jsx
  src/component/location/LocationList.jsx
  src/component/location/LocationModal.jsx
  src/component/weather/CurrentWeather.jsx
  src/component/weather/HourlyWeather.jsx
  src/pages/Main.jsx
  src/pages/Weather.jsx
  src/utils/descMapper.js
Labels: Feat

#16 날씨 api 재연결 및 리팩토링, 오류 수정
  src/apis/fetchWeather.js
  src/component/weather/CurrentWeather.jsx
  src/component/weather/details/AirBox.jsx
  src/index.jsx
  src/pages/Weather.jsx
  src/utils/weatherStyles.js
Labels: Bug, Feat, Refactor

#17 로딩, 모달, 버튼 등 주요 인터랙션 개선
  src/component/location/DeleteModal.jsx
  src/component/location/Location.jsx
  src/component/location/LocationList.jsx
  src/component/location/LocationModal.jsx
  src/component/ui/CenteredBox.jsx
  src/component/ui/Spinner.jsx
  src/hooks/useEscapeClose.js
  src/pages/Main.jsx
  src/pages/Weather.jsx
Labels: Bug, Feat, UI
